Fix release note button clicking crash
topjohnwu/MagiskManager pull request #136
Opened 2017-03-20 11:58 UTC by aviraxp

As for context, we should set this flag. Also check for null when there is no internet.

2017-03-20 17:45 UTC, TheComputerGuy96 requested changes
You made some typos

2017-03-20 17:45 UTC, TheComputerGuy96 commented on app/src/main/java/com/topjohnwu/magisk/InstallFragment.java
> +                        Intent openReleasNoteLink = new Intent(Intent.ACTION_VIEW, Uri.parse(magiskManager.releaseNoteLink));
Typo

2017-03-20 17:45 UTC, TheComputerGuy96 commented on app/src/main/java/com/topjohnwu/magisk/InstallFragment.java
> +                        magiskManager.startActivity(openReleasNoteLink);
Typo

2017-03-20 17:45 UTC, TheComputerGuy96 commented on app/src/main/java/com/topjohnwu/magisk/InstallFragment.java
> +                        openReleasNoteLink.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
Typo

2017-03-26 15:54 UTC, topjohnwu commented
Thanks, this crash happens on Samsung only too :)

2017-03-26 15:55 UTC, merged

2017-03-27 03:59 UTC, aviraxp commented
No, it happens on almost every device I have.